<a href="https://colab.research.google.com/github/shubhamsiddhapura/Weather_App/blob/main/MLPrac4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#ML PRAC 4

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv('/content/titanic.csv')

In [ ]:
data.head(10)

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   
5            6                                   Moran, Mr. James       3   
6            7                            McCarthy, Mr. Timothy J       1   
7            8                     Palsson, Master. Gosta Leonard       3   
8            9  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)       3   
9           10                Nasser, Mrs. Nicholas (Adele Achem)       2   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   
5    male   NaN      0      0            330877   8.4583   NaN        Q   
6    male  54.0      0      0             17463  51.8625   E46        S   
7    male   2.0      3      1            349909  21.0750   NaN        S   
8  female  27.0      0      2            347742  11.1333   NaN        S   
9  female  14.0      1      0            237736  30.0708   NaN        C   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0  
5         0  
6         0  
7         0  
8         1  
9         1

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Name         891 non-null    object 
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object 
 10  Embarked     889 non-null    object 
 11  Survived     891 non-null    int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
data.drop(['PassengerId','Name','Ticket','Cabin','Embarked','SibSp','Parch'],axis='columns',inplace=True)
data.head(10)

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0
5       3    male   NaN   8.4583         0
6       1    male  54.0  51.8625         0
7       3    male   2.0  21.0750         0
8       3  female  27.0  11.1333         1
9       2  female  14.0  30.0708         1

In [ ]:
inputs = data.drop('Survived',axis='columns')
target = data.Survived

In [ ]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

female   male
0   False   True
1    True  False
2    True  False

In [ ]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False

In [ ]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True

In [ ]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [ ]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [ ]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(inputs,target,test_size=0.2)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [ ]:
model.fit(x_train,y_train)

GaussianNB()

In [ ]:
model.score(x_test,y_test)

0.7821229050279329

In [ ]:
y_test[0:10]

854    0
619    0
94     0
753    0
561    0
66     1
335    0
718    0
446    1
346    1
Name: Survived, dtype: int64

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),x_train, y_train, cv=5)

array([0.81118881, 0.81818182, 0.76760563, 0.75352113, 0.72535211])

In [ ]:
model.predict(x_test[0:10])

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 1])

In [ ]:
model.predict_proba(x_test[:10])

array([[0.27417753, 0.72582247],
       [0.92727136, 0.07272864],
       [0.95904093, 0.04095907],
       [0.96139019, 0.03860981],
       [0.96600159, 0.03399841],
       [0.27227476, 0.72772524],
       [0.96445772, 0.03554228],
       [0.96531526, 0.03468474],
       [0.21968608, 0.78031392],
       [0.28455404, 0.71544596]])