<a href="https://colab.research.google.com/github/shubhamsiddhapura/Weather_App/blob/main/MLPrac1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#ML PRAC 1

In [ ]:
"""
Package for statistics
  1. statistics
  2. numpy
  3. pandas
  4. scipy
"""

'\nPackage for statistics\n  1. statistics\n  2. numpy\n  3. pandas\n  4. scipy\n'

In [ ]:
import statistics as st

In [ ]:
#finding mean

age = [20, 19, 20, 18, 21, 22]

n_age = st.mean(age)
print("Mean age : ", n_age)

Mean age :  20


In [ ]:
#finding mean 2

age = [20, 19, 20, 18, 21, 22, 70]

n_age = st.mean(age)
print("Mean age : ", n_age)

Mean age :  27.142857142857142


In [ ]:
#finding median

age = [20, 19, 20, 18, 21, 22]

n_age = st.median(age)
print("Median age : ", n_age)

Median age :  20.0


In [ ]:
#finding median 2

age = [20, 19, 20, 18, 21, 22, 70]

n_age = st.median(age)
print("Median age : ", n_age)

Median age :  20


In [ ]:
#finding mode

s_scores = [1, 2, 3, 1, 2, 2, 2, 4, 3, 3, 1]

n_s_scores = st.mode(s_scores)
print("Mode age : ", n_s_scores)

Mode age :  2


In [ ]:
#finding range

age = [20, 19, 20, 18, 21, 22]

n_age = st.stdev(age)
print("Range age : ", n_age)

Range age :  1.4142135623730951


In [ ]:
#finding range 2

age = [20, 19, 20, 18, 21, 22, 70]

n_age = st.stdev(age)
print("Range age : ", n_age)

Range age :  18.942268180171133


In [ ]:
#finding variance

age = [20, 19, 20, 18, 21, 22]

n_age = st.variance(age)
print("Variance age : ", n_age)

Variance age :  2


In [ ]:
#finding variance 2

age = [20, 19, 20, 18, 21, 22, 70]

n_age = st.variance(age)
print("Variance age : ", n_age)

Variance age :  358.8095238095238


In [ ]:
import numpy as np

In [ ]:
a1 = np.array(20)

print(a1)
print("Dim ", a1.ndim)

20
Dim  0


In [ ]:
a2 = np.array([10, 20, 30, 10, 30, 405, 505, 50, 50])

print(a2)
print("Dim ", a2.ndim)

[ 10  20  30  10  30 405 505  50  50]
Dim  1


In [ ]:
a3 = np.array([[10, 20, 30], [10, 30, 405], [505, 50, 50]])

print(a3)
print("Dim", a3.ndim)

[[ 10  20  30]
 [ 10  30 405]
 [505  50  50]]
Dim 2


In [ ]:
a4 = np.array([[[[10]]]])

print(a4)
print("Dim ", a4.ndim)

[[[[10]]]]
Dim  4


In [ ]:
a3 = np.array([[10, 20, 30], [10, 30, 405], [505, 50, 50]], dtype=np.int16)

print(a3)
print("Dim ", a3.ndim)
print("Shape ", a3.shape)
print("Size ", a3.size)
print("Item Size ", a3.itemsize)
print("Data Type ", a3.dtype)

[[ 10  20  30]
 [ 10  30 405]
 [505  50  50]]
Dim  2
Shape  (3, 3)
Size  9
Item Size  2
Data Type  int16


In [ ]:
a4 = np.array([[[1], [1]], [[1], [1]]])

print("Shape ", a4.shape)
print("Size ", a4.size)

Shape  (2, 2, 1)
Size  4


In [ ]:
#array with junk/random numbers

a11 = np.empty((5, 5))

a11

array([[ 4.97346853e-310,  0.00000000e+000,  6.84289373e-310,
         6.84289373e-310,  6.84290308e-310],
       [ 6.84289373e-310,  6.84289421e-310,  6.84289463e-310,
         6.84290309e-310,  6.84290309e-310],
       [ 6.84290453e-310,  6.84290453e-310,  6.84289376e-310,
         7.45263174e+260,  6.84289373e-310],
       [ 6.84289376e-310,  1.51249816e+105,  6.84289376e-310,
         6.84289376e-310, -2.74720881e-245],
       [ 6.84289375e-310,  6.84289376e-310, -1.48389371e-175,
         6.84289421e-310,  1.58101007e-321]])

In [ ]:
#array with zeros

a12 = np.zeros((3, 5))

a12

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#array with ones

a13 = np.ones((4, 4))

a13

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#a14 = np.arange(100)
#a14 = np.arange(1, 101)

a14 = np.arange(2, 101, 2)

a14

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
#reshaping array a14 to 10 rows and 5 columns

a15 = np.reshape(a14, (10, 5))

a15

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [ ]:
a14 = np.reshape(a14, (2, 5, 5))

a14

array([[[  2,   4,   6,   8,  10],
        [ 12,  14,  16,  18,  20],
        [ 22,  24,  26,  28,  30],
        [ 32,  34,  36,  38,  40],
        [ 42,  44,  46,  48,  50]],

       [[ 52,  54,  56,  58,  60],
        [ 62,  64,  66,  68,  70],
        [ 72,  74,  76,  78,  80],
        [ 82,  84,  86,  88,  90],
        [ 92,  94,  96,  98, 100]]])

In [ ]:
a1 = np.arange(10)

a2 = np.arange(11, 21)

print(a1, a2)

[0 1 2 3 4 5 6 7 8 9] [11 12 13 14 15 16 17 18 19 20]


In [ ]:
#arithmetic operations by using scalar

print(a1+2)
print(a1*2)
print(a1/2)
print(a1**2)

[ 2  3  4  5  6  7  8  9 10 11]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 0  1  4  9 16 25 36 49 64 81]


In [ ]:
#arithmetic operations using vector

print(a1+a2)
print(a1*a2)
print(a1/a2)
print(a1**a2)

[11 13 15 17 19 21 23 25 27 29]
[  0  12  26  42  60  80 102 126 152 180]
[0.         0.08333333 0.15384615 0.21428571 0.26666667 0.3125
 0.35294118 0.38888889 0.42105263 0.45      ]
[                   0                    1                 8192
              4782969           1073741824         152587890625
       16926659444736     1628413597910449   144115188075855872
 -6289078614652622815]


In [ ]:
#random numbers

print(np.random.rand())
print(np.random.randn())
print(np.random.rand(2, 5, 2))

0.675707144258379
0.04547220424241208
[[[0.01039197 0.72289522]
  [0.23741511 0.60870328]
  [0.54229544 0.84358913]
  [0.26217342 0.46779989]
  [0.9908857  0.06663636]]

 [[0.3547358  0.58089513]
  [0.9382128  0.99257209]
  [0.26869196 0.02104401]
  [0.5754659  0.18569764]
  [0.01377449 0.3582348 ]]]


In [ ]:
a1 = np.arange(10, 100, 10)
a1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print('1st ele: ', a1[0])

1st ele:  10


In [ ]:
print('5th ele: ', a1[4])

5th ele:  50


In [ ]:
print('last ele: ', a1[-1])

last ele:  90


In [ ]:
print('2nd ele from rev end: ', a1[-2])

2nd ele from rev end:  80


In [ ]:
print('1st 5 eles: ', a1[:5])

1st 5 eles:  [10 20 30 40 50]


In [ ]:
print('last 5 eles: ', a1[-5:])

last 5 eles:  [50 60 70 80 90]


In [ ]:
print('alternate eles: ', a1[::2])

alternate eles:  [10 30 50 70 90]


In [ ]:
a12 = np.arange(1,101)
a12 = np.reshape(a12, (10,10))

a12

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
print('1st and last row values from coulmns 4 to 8')
print(a12[[0, -1], 3:8])

1st and last row values from coulmns 4 to 8
[[ 4  5  6  7  8]
 [94 95 96 97 98]]


In [ ]:
a1 = np.array([10, 5, 20, 8, 7, 4,  5])

a1

array([10,  5, 20,  8,  7,  4,  5])

In [ ]:
np.unique(a1)

array([ 4,  5,  7,  8, 10, 20])

In [ ]:
np.sort(a1)[::-1]

array([20, 10,  8,  7,  5,  5,  4])

In [ ]:
np.argmax(a1)

2

In [ ]:
import pandas as pd

In [ ]:
prod_dict = {
    'pid': [10, 20, 30, 40],
    'pname': ['Laptop', 'Mobile', 'TV', 'AC'],
    'price': [10000, 20000, 30000, 40000],
    'vendor': ['ABC', 'XYZ', 'PQR', 'LMN']
}

prod_dict

{'pid': [10, 20, 30, 40],
 'pname': ['Laptop', 'Mobile', 'TV', 'AC'],
 'price': [10000, 20000, 30000, 40000],
 'vendor': ['ABC', 'XYZ', 'PQR', 'LMN']}

In [ ]:
prod_df = pd.DataFrame(prod_dict)

prod_df

pid   pname  price vendor
0   10  Laptop  10000    ABC
1   20  Mobile  20000    XYZ
2   30      TV  30000    PQR
3   40      AC  40000    LMN

In [ ]:
prod_df.size

16

In [ ]:
prod_df.dtypes

pid        int64
pname     object
price      int64
vendor    object
dtype: object

In [ ]:
prod_df.index

RangeIndex(start=0, stop=4, step=1)